In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
list=[1,2,3,4,5]
arr=np.array(list)
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([100,"pragna","kruthi",True])
print(arr)

['100' 'pragna' 'kruthi' 'True']


In [ ]:
import numpy as np
arr=np.array((1,"pragna",True))
print(arr)
print(type(arr))

['1' 'pragna' 'True']
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array(["p,r,a,g,n,a"])
print(arr)

['p,r,a,g,n,a']


In [ ]:
for (int i=0;i<100;i++)
{
    total+=array[i]; // ,total;is reused on every iteration
}

SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-2842414390.py, line 1)

In [ ]:
for (int i=0; i<100; i++)
{
    sum+=array[i];
}

SyntaxError: invalid syntax. Perhaps you forgot a comma? (ipython-input-79269834.py, line 1)

In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5,"pragna"))
print(arr)

['1' '2' '3' '4' '5' 'pragna']


In [ ]:
import numpy as np
arr=np.array(72)
print(arr)

72


In [ ]:
import numpy as np
list={
    "roll no": 72
}
arr=np.array(list)
print(arr)

{'roll no': 72}


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
list={
    "name" : "pragna",
    "roll no":"AMB2172"
}
arr=np.array(list)
print(arr)

{'name': 'pragna', 'roll no': 'AMB2172'}


In [ ]:
import numpy as np
arr=np.array({"name" : "pragna","roll no":"AMB2172"})
print(arr)

{'name': 'pragna', 'roll no': 'AMB2172'}


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
arr=np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array(({"name":"pragna"},{"id no":"AMB2172"}))
print(arr)

[{'name': 'pragna'} {'id no': 'AMB2172'}]


In [ ]:
import numpy as np
arr=np.array(([{"name":"pragna"}],[{"id no":"AMB2172"}]))
print(arr)

[[{'name': 'pragna'}]
 [{'id no': 'AMB2172'}]]


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [ ]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=6)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions: 6


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 4

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1]+arr[3])

6


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,0])

5


In [ ]:
#from python list
arr=np.array([12,14,16,18,20])

#2D array
arr_2d=np.array([[10,20,30],[40,50,60]])

#built in functions
zeros=np.zeros((4,5))
ones=np.ones((3,4))
range_arr=np.arange(0,30,3)
linspace=np.linspace(0,10,50)
identity=np.eye(4)
random_arr=np.random.rand(3,4)
print(arr)
print(arr_2d)
print(zeros)
print(ones)
print(range_arr)
print(linspace)
print(identity)
print(random_arr)

[12 14 16 18 20]
[[10 20 30]
 [40 50 60]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.46080383 0.53923898 0.29856118 0.76338419]
 [0.78858534 0.25176761 0.23108078 0.03292143]
 [0.65134514 0.32169764 0.12266631 0.16024

In [ ]:
linspace=np.linspace(0,2,6)
print(linspace)

[0.  0.4 0.8 1.2 1.6 2. ]


In [ ]:
random_arr=np.random.rand(3,3)
print(random_arr)

[[0.28828962 0.51395504 0.53373974]
 [0.11747035 0.66595967 0.2738672 ]
 [0.88822258 0.58692773 0.34351315]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a=np.array([[[2,3,4],[5,7,8]],[[4,6,8],[3,8,5]]])
print(a)
print(a.shape)

[[[2 3 4]
  [5 7 8]]

 [[4 6 8]
  [3 8 5]]]
(2, 2, 3)


In [ ]:
a=np.array([[[2.2,3.9,4],[5.3,7,8.4]],[[4,6,8],[3,8,5]]])
print(a)
print(a.dtype)

[[[2.2 3.9 4. ]
  [5.3 7.  8.4]]

 [[4.  6.  8. ]
  [3.  8.  5. ]]]
float64


In [ ]:
import numpy as np
a=[28,44,54,68]
b=np.array(a)
print(b.size)

4


In [ ]:
a=[28,44,54,68]
b=np.array(a)
print(b.ndim)

1


In [ ]:
import numpy as np
b=np.array(10)
print(b.ndim)

0


In [ ]:
a=[[2,4,5,7,8],[3,4,5,6,7]]
b=np.array(a)
print(b.ndim)

2


In [ ]:
a=[[2,4,5,7,8],[3,4,5,6,7]]
b=np.sum(a)
print(b)

51


In [ ]:
a=[[2,4,5,7,8],[3,4,5,6,7]]
arr=np.array(a)
b=np.mean(a,axis=0)
c=np.mean(a,axis=1)
print(arr)
print(b)
print(c)

[[2 4 5 7 8]
 [3 4 5 6 7]]
[2.5 4.  5.  6.5 7.5]
[5.2 5. ]


In [ ]:
b=np.max(a)
print(b)

8


In [ ]:
b=np.min(a)
print(b)

2


In [ ]:
b=np.array([10,40,30])
c=np.argmax(b)
print(c)

1


In [ ]:
b=np.array([[2,4,5,7,8],[3,4,5,6,7]])
c=np.argmax(b)
print(c)

4


In [ ]:
import numpy as np
crop_yields=np.array([
    [12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.1,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3,11.7,12.8]
])
print('crop yields array(tons):')
print(crop_yields)
print(f'\nshape:{crop_yields.shape}')
print(f'\ndata type:{crop_yields.dtype}')
print(f'\ntotal elements:{crop_yields.size}')
print(f'\nnumber of dimensions:{crop_yields.ndim}')

#Agricultural analysis operations
total_yield = np.sum(crop_yields)
avg_yield_per_farm = np.mean(crop_yields, axis=1)
avg_yield_per_season = np.mean(crop_yields, axis=0)
max_yield = np.max(crop_yields)
min_yield = np.min(crop_yields)

print(f'\nTotal production: {total_yield} tons')
print(f'Average per farm: {avg_yield_per_farm} tons')
print(f'Average per season: {avg_yield_per_season} tons')
print(f'Maximum yield: {max_yield} tons')
print(f'Minimum yield: {min_yield} tons')

# Find best performing farm
best_farm = np.argmax(avg_yield_per_farm)
print(f'\nBest performing farm: Farm {best_farm + 1}')
print(f'Their average yield: {avg_yield_per_farm[best_farm]:.2f} tons')




crop yields array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

shape:(4, 5)

data type:float64

total elements:20

number of dimensions:2

Total production: 262.7 tons
Average per farm: [13.76 11.32 15.68 11.78] tons
Average per season: [12.275 12.6   13.35  13.275 14.175] tons
Maximum yield: 16.8 tons
Minimum yield: 10.3 tons

Best performing farm: Farm 3
Their average yield: 15.68 tons


In [ ]:
crop_yields=np.array([
    [12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.1,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3,11.7,12.8]
])
print(f'\nnumber of dimensions:{crop_yields.ndim}')


number of dimensions:2


In [ ]:
import numpy as np
arr=np.array([2,1,5,3,7,4,6,8])
print(arr)
np.sort(arr)

[2 1 5 3 7 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.argsort(arr)

array([1, 0, 3, 5, 2, 6, 4, 7])

In [ ]:
#numpy.argsort
import numpy as np
x=np.array([3,1,2])
np.argsort(x)

array([1, 2, 0])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
np.concatenate((x,y),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#arr.reshape()
a=np.arange(6)
print(a)
b=a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
#indexing and slicing
data=np.array([1,2,3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[a<5])
print("\n")
five_up=(a>=5)
print(a[five_up])
print("\n")
divisible_by_2=a[a%2==0]
print(divisible_by_2)
print("\n")
c=a[(a>2)&(a<11)]
print(c)
print("\n")
five_up=(a>5) | (a==5)
print(five_up)

[1 2 3 4]


[ 5  6  7  8  9 10 11 12]


[ 2  4  6  8 10 12]


[ 3  4  5  6  7  8  9 10]


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
#converting distance in miles to kilometers
data=np.array([1.0,2.0])
data*1.6

array([1.6, 3.2])

In [ ]:
import numpy as np
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [18]:
import numpy as np

# Create a 10x5 array with values from 0 to 49
a = np.arange(50).reshape(10, 5)
print("Original array (10x5):\n", a)

# Select all rows where the first feature (column 0) is greater than 20
print(a[:])
print(a[:1])
print(a[:,3])
print(a[:,1])
selected_rows = a[a[:,0] > 20]
print("\nRows where first feature > 20:\n", selected_rows)

Original array (10x5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[0 1 2 3 4]]
[ 3  8 13 18 23 28 33 38 43 48]
[ 1  6 11 16 21 26 31 36 41 46]

Rows where first feature > 20:
 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
