In [ ]:
import numpy as np
x=np.arange(10)
x=x[x%2==0]*2
print(x)


[ 0  4  8 12 16]


In [ ]:
import numpy as np
x=np.arange(10)
x=x[x%2==0]
print(x)

[0 2 4 6 8]


In [ ]:
import numpy as np
x=np.arange(10)
x=x*[x%2==0]
print(x)

[[0 0 2 0 4 0 6 0 8 0]]


In [1]:
import numpy as np
a=np.arange(50).reshape(10,5)
selected_rows=a[a[:,0]>20]
print(selected_rows)

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [55]:
a=np.array([[1,2,3],[4,5,6]]).reshape(6,)
print(a)

[1 2 3 4 5 6]


In [2]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]],dtype=bool)
c=a[b]
print(c)

[1 3 5]


In [9]:
a=np.array([[1,2,7],[3,4,9],[5,6,8]])
mask=np.array([[True,False,True],[True,False,True],[True,False,True]])
b=a[mask]
print(b)

[1 7 3 9 5 8]


In [ ]:
a=np.array([[1,2,7],[3,4,9],[5,6,8]])
mask=np.array([[True,False,True]])
b=a[mask]
print(b)

In [4]:
a=np.array([0.3,0.5,0.1,1,3])
print(a[a>0.5])

[1. 3.]


In [16]:
a=np.array([[1,2],[3,4],[5,6]])
b=a[a[:,1]%2==0]
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
a=np.array([[2,9],[3,7],[5,6]])
b=a[a[:,1]%2==0]
print(b)

[[5 6]]


In [10]:
import numpy as np
x=np.array([1,2,3,4,5])
mask=(x%2==0)
print(mask)


[False  True False  True False]


In [12]:
a=np.array([[1,2,3],[4,5,6]])
b=(a>2)&(a<6)
print(b)

[[False False  True]
 [ True  True False]]


In [20]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
c=a*b
print(c.shape)

(2, 3)


In [21]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
c=a+b
print(c.shape)

(2, 3)


In [28]:
a=np.array([1,8,3,4,5,6])
a[a>3]= 0
print(a)

[1 0 3 0 0 0]


In [27]:
a=np.array([1,7,3,4,5,6])
a[3:]= 0
print(a)

[1 7 3 0 0 0]


In [31]:
a=np.array([10,20,30,40,50])
mask=np.array([True,False,True,False,True])
b=a[mask]
print(b)

[10 30 50]


In [32]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[:,1])

[2 4 6]


In [47]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[a[a:,1]>2])

TypeError: only integer scalar arrays can be converted to a scalar index

In [33]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[:,[False,True]])

[[2]
 [4]
 [6]]


In [51]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[[False,True,False],:])

[[3 4 4]]


In [53]:
a=np.array([[1,2,8],[3,4,4],[5,6,7]])
print(a[:,[False,True,False]])

[[2]
 [4]
 [6]]


In [37]:
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
mask=np.array([True,False,True])
print(arr[mask])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [38]:
a=np.array([1,2,3,4,5])
print(a[a>2])

[3 4 5]


In [39]:
a=np.array([1,2,3,4,5,6])
mask=np.array([True,False,True,False,True,False])
b=a[mask]*10
print(b)

[10 30 50]


In [40]:
a=np.array([10,20,30,40,50])
idx=np.array([4,0,4,1])
print(a[idx])

[50 10 50 20]


In [42]:
a=np.array([10,20,30,40,50])
mask=a>25
print(a[mask])
idx=np.array([2,3])
print(a[idx])


[30 40 50]
[30 40]


In [43]:
a=np.array([[1,2],[3,4]])
b=np.array([10,20,30])
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [54]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
c=a+b
print(c)
print(c.shape)

[[ 8 10 12]
 [11 13 15]]
(2, 3)
